name: Auto update DB
on:
  push:
  schedule:
    - cron: '0 1 * * *'

jobs:
  run:
    name: Update dedaluz's prices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 19.x

      - name: Run the update
        run: node scrape.js

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Updated CEX products'
          add: '*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}